################################################# 
# Program to read variable of a nc file 
# using python with NetCdf
# Create by: Jhonatan Aguirre 
# Date:06/02/2020
# working:yes
#################################################

# Python library to work with Netcdf4 
from    netCDF4         import Dataset

# To save the time coordinate in specific format 
from    netCDF4         import num2date, date2num

from    cftime          import num2date, num2pydate

import datetime as dt


class variables(object):

    def __init__(self):

        self.datei       = 'datei'      
        self.datef       = 'datef'
        self.name        = 'name'
        self.vars_to_plot= 'vars_to_plot'
        self.date       = 'date' 
        #####################################
        self.z          = 'z'
        self.time       = 'time'
        self.p          = 'p'             
        self.SST        = 'SST'
        self.Ps         = 'Ps'
        self.CLD245     = 'CLD245'
        self.PREC       = 'PREC'
        self.LHF        = 'LHF'
        self.SHF        = 'SHF'
        self.PW         = 'PW' 
        self.IWP        = 'IWP'  
        self.GWP        = 'GWP'        
        self.CAPE       = 'CAPE' 
        self.CAPEOBS    = 'CAPEOBS'
        self.CIN        = 'CIN'
        self.CINOBS     = 'CINOBS'
        self.LWNS       = 'LWNS'
        self.LWNT       = 'LWNT'
        self.LWNTOA     = 'LWNTOA'
        self.LWNSC      = 'LWNSC'
        self.LWNTOAC    = 'LWNTOAC'
        self.LWDS       = 'LWDS'
        self.SWNS       = 'SWNS'
        self.SWNT       = 'SWNT'
        self.SWNTOA     = 'SWNTOA'
        self.SWNSC      = 'SWNSC'
        self.SWNTOAC    = 'SWNTOAC'
        self.SWDS       = 'SWDS'
        self.SOLIN      = 'SOLIN'
        self.SSTOBS     = 'SSTOBS'
        self.LHFOBS     = 'LHFOBS'
        self.SHFOBS     = 'SHFOBS'
        self.CLDLOW     = 'CLDLOW'
        self.ISCCPTOT   = 'ISCCPTOT'
        self.ISCCPHGH   = 'ISCCPHGH'
        self.MODISTOT   = 'MODISTOT'
        self.MODISMID   = 'MODISMID'
        self.MODISREL   = 'MODISREL'
        self.MODISIWP   = 'MODISIWP'
        self.MODISTOTL  = 'MODISTOTL'
        self.ISCCPALB   = 'ISCCPALB'
        self.MODISTAUL  = 'MODISTAUL'
        self.MODISTAUI  = 'MODISTAUI'
        self.MODISPTOP  = 'MODISPTOP'
        self.MISRZTOP   = 'MISRZTOP'
        self.ZINV       = 'ZINV'
        self.ZINV2      = 'ZINV2'
        self.ZCT        = 'ZCT'
        self.ZCT2       = 'ZCT2'
        self.ZCTMAX     = 'ZCTMAX'
        self.ZCB        = 'ZCB'
        self.ZCB2       = 'ZCB2'
        self.ZCBMIN     = 'ZCBMIN'
        self.LWP        = 'LWP'
        self.LWP2       = 'LWP2'
        self.PRECMN     = 'PRECMN'
        self.PREC2      = 'PREC2'
        self.PRECMAX    = 'PRECMAX'
        self.NCMN       = 'NCMN'
        self.NRMN       = 'NRMN'
        self.AREAPRTHR  = 'AREAPRTHR'
        self.PRES       = 'PRES'
        self.U          = 'U'
        self.V          = 'V'
        self.UOBS       = 'UOBS'
        self.VOBS       = 'VOBS'
        self.WOBS       = 'WOBS'
        self.RHO        = 'RHO'
        self.MSE        = 'MSE'
        self.DSE        = 'DSE'
        self.SSE        = 'SSE'
        self.THETAE     = 'THETAE'
        self.THETA      = 'THETA'
        self.THETAV     = 'THETAV'
        self.THETAL     = 'THETAL'
        self.TABS       = 'TABS'
        self.TABSOBS    = 'TABSOBS'
        self.TL         = 'TL'
        self.QT         = 'QT'
        self.QV         = 'QV'
        self.QVOBS      = 'QVOBS'
        self.TTEND      = 'TTEND'
        self.QTEND      = 'QTEND'
        self.QCL        = 'QCL'
        self.QCI        = 'QCI'
        self.QPL        = 'QPL'
        self.QPI        = 'QPI'
        self.QN         = 'QN'
        self.QP         = 'QP'
        self.QSAT       = 'QSAT'
        self.QCOND      = 'QCOND'
        self.PRECIP     = 'PRECIP'
        self.RELH       = 'RELH'
        self.TLFLUX     = 'TLFLUX'
        self.TLFLUXS    = 'TLFLUXS'
        self.TVFLUX     = 'TVFLUX'
        self.QCFLUX     = 'QCFLUX'
        self.QIFLUX     = 'QIFLUX'
        self.UW         = 'UW'
        self.UWSB       = 'UWSB'
        self.VW         = 'VW'
        self.VWSB       = 'VWSB'
        self.RADLWUP    = 'RADLWUP'
        self.RADLWDN    = 'RADLWDN'
        self.RADSWUP    = 'RADSWUP'
        self.RADSWDN    = 'RADSWDN'
        self.RADQRLW    = 'RADQRLW'
        self.RADQRSW    = 'RADQRSW'
        self.RADQR      = 'RADQR'
        self.RADQRS     = 'RADQRS'
        self.RADQRC     = 'RADQRC'
        self.Q1C        = 'Q1C'
        self.Q2         = 'Q2'
        self.U2         = 'U2'
        self.V2         = 'V2'
        self.W2         = 'W2'
        self.TL2        = 'TL2'
        self.TQ         = 'TQ'
        self.QT2        = 'QT2'
        self.QC2        = 'QC2'
        self.QI2        = 'QI2'
        self.QS2        = 'QS2'
        self.W3         = 'W3'
        self.AUP        = 'AUP'
        self.WSKEW      = 'WSKEW'
        self.TKE        = 'TKE'
        self.TKES       = 'TKES'
        self.TK         = 'TK'
        self.TKH        = 'TKH'
        self.HLADV      = 'HLADV'
        self.HLDIFF     = 'HLDIFF'
        self.HLLAT      = 'HLLAT'
        self.HLRAD      = 'HLRAD'
        self.QTADV      = 'QTADV'
        self.QTDIFF     = 'QTDIFF'
        self.QTSINK     = 'QTSINK'
        self.QTSRC      = 'QTSRC'
        self.QPADV      = 'QPADV'
        self.QPDIFF     = 'QPDIFF'
        self.QPFALL     = 'QPFALL'
        self.QPSRC      = 'QPSRC'
        self.QPEVP      = 'QPEVP'
        self.SHEAR      = 'SHEAR'
        self.SHEARS     = 'SHEARS'
        self.BUOYA      = 'BUOYA'
        self.BUOYAS     = 'BUOYAS'
        self.ADVTR      = 'ADVTR'
        self.PRESSTR    = 'PRESSTR'
        self.ADVTRS     = 'ADVTRS'
        self.DIFTR      = 'DIFTR'
        self.DISSIP     = 'DISSIP'
        self.DISSIPS    = 'DISSIPS'
        self.WUADV      = 'WUADV'
        self.WVADV      = 'WVADV'
        self.WUPRES     = 'WUPRES'
        self.WVPRES     = 'WVPRES'
        self.WUANIZ     = 'WUANIZ'
        self.WVANIZ     = 'WVANIZ'
        self.WUSHEAR    = 'WUSHEAR'
        self.WVSHEAR    = 'WVSHEAR'
        self.WUBUOY     = 'WUBUOY'
        self.WVBUOY     = 'WVBUOY'
        self.WUDIFF     = 'WUDIFF'
        self.WVDIFF     = 'WVDIFF'
        self.W2ADV      = 'W2ADV'
        self.W2PRES     = 'W2PRES'
        self.W2REDIS    = 'W2REDIS'
        self.W2BUOY     = 'W2BUOY'
        self.W2DIFF     = 'W2DIFF'
        self.TWGRAD     = 'TWGRAD'
        self.TWADV      = 'TWADV'
        self.TWDIFF     = 'TWDIFF'
        self.TWBUOY     = 'TWBUOY'
        self.TWPRES     = 'TWPRES'
        self.TWPREC     = 'TWPREC'
        self.QWGRAD     = 'QWGRAD'
        self.QWADV      = 'QWADV'
        self.QWDIFF     = 'QWDIFF'
        self.QWBUOY     = 'QWBUOY'
        self.QWPRES     = 'QWPRES'
        self.QWPREC     = 'QWPREC'
        self.T2ADVTR    = 'T2ADVTR'
        self.T2GRAD     = 'T2GRAD'
        self.T2DISSIP   = 'T2DISSIP'
        self.T2DIFTR    = 'T2DIFTR'
        self.T2PREC     = 'T2PREC'
        self.Q2ADVTR    = 'Q2ADVTR'
        self.Q2GRAD     = 'Q2GRAD'
        self.Q2DISSIP   = 'Q2DISSIP'
        self.Q2DIFTR    = 'Q2DIFTR'
        self.Q2PREC     = 'Q2PREC'
        self.HYDRO      = 'HYDRO'
        self.MCUP       = 'MCUP'
        self.MCDNS      = 'MCDNS'
        self.MCDNU      = 'MCDNU'
        self.MC         = 'MC'
        self.CORECL     = 'CORECL'
        self.COREDNCL   = 'COREDNCL'
        self.MCRUP      = 'MCRUP'
        self.MCRDNS     = 'MCRDNS'
        self.MCRDNU     = 'MCRDNU'
        self.MCR        = 'MCR'
        self.QVTEND     = 'QVTEND'
        self.QHTEND     = 'QHTEND'
        self.QNUDGE     = 'QNUDGE'
        self.THTEND     = 'THTEND'
        self.TVTEND     = 'TVTEND'
        self.TNUDGE     = 'TNUDGE'
        self.WSTAR3     = 'WSTAR3'
        self.UADV       = 'UADV'
        self.VADV       = 'VADV'
        self.UDIFF      = 'UDIFF'
        self.VDIFF      = 'VDIFF'
        self.UNUDGE     = 'UNUDGE'
        self.VNUDGE     = 'VNUDGE'
        self.ULSADVV    = 'ULSADVV'
        self.VLSADVV    = 'VLSADVV'
        self.USTOR      = 'USTOR'
        self.VSTOR      = 'VSTOR'
        self.UTENDCOR   = 'UTENDCOR'
        self.URESID     = 'URESID'
        self.VTENDCOR   = 'VTENDCOR'
        self.VRESID     = 'VRESID'
        self.HLSTOR     = 'HLSTOR'
        self.QTSTOR     = 'QTSTOR'
        self.RADQRCLW   = 'RADQRCLW'
        self.RADQRCSW   = 'RADQRCSW'
        self.CLD        = 'CLD'
        self.WCLD       = 'WCLD'
        self.UCLD       = 'UCLD'
        self.VCLD       = 'VCLD'
        self.MSECLD     = 'MSECLD'
        self.DSECLD     = 'DSECLD'
        self.TLCLD      = 'TLCLD'
        self.TACLD      = 'TACLD'
        self.TVCLD      = 'TVCLD'
        self.TVCLDA     = 'TVCLDA'
        self.QTCLD      = 'QTCLD'
        self.QNCLD      = 'QNCLD'
        self.QPCLD      = 'QPCLD'
        self.WCLDA      = 'WCLDA'
        self.TLWCLD     = 'TLWCLD'
        self.TVWCLD     = 'TVWCLD'
        self.QTWCLD     = 'QTWCLD'
        self.QCWCLD     = 'QCWCLD'
        self.QIWCLD     = 'QIWCLD'
        self.HFCLD      = 'HFCLD'
        self.HFCLDA     = 'HFCLDA'
        self.UCLDA      = 'UCLDA'
        self.VCLDA      = 'VCLDA'
        self.UPGFCLD    = 'UPGFCLD'
        self.VPGFCLD    = 'VPGFCLD'
        self.WPGFCLD    = 'WPGFCLD'
        self.UWCLD      = 'UWCLD'
        self.VWCLD      = 'VWCLD'
        self.UWSBCLD    = 'UWSBCLD'
        self.VWSBCLD    = 'VWSBCLD'
        self.MFCLD      = 'MFCLD'
        self.MFHCLD     = 'MFHCLD'
        self.MFHCLDA    = 'MFHCLDA'
        self.MFTLCLD    = 'MFTLCLD'
        self.MFTLCLDA   = 'MFTLCLDA'
        self.MFTVCLD    = 'MFTVCLD'
        self.MFTVCLDA   = 'MFTVCLDA'
        self.MFQTCLD    = 'MFQTCLD'
        self.MFQTCLDA   = 'MFQTCLDA'
        self.RUWCLD     = 'RUWCLD'
        self.RVWCLD     = 'RVWCLD'
        self.RWWCLD     = 'RWWCLD'
        self.COR        = 'COR'
        self.WCOR       = 'WCOR'
        self.UCOR       = 'UCOR'
        self.VCOR       = 'VCOR'
        self.MSECOR     = 'MSECOR'
        self.DSECOR     = 'DSECOR'
        self.TLCOR      = 'TLCOR'
        self.TACOR      = 'TACOR'
        self.TVCOR      = 'TVCOR'
        self.TVCORA     = 'TVCORA'
        self.QTCOR      = 'QTCOR'
        self.QNCOR      = 'QNCOR'
        self.QPCOR      = 'QPCOR'
        self.WCORA      = 'WCORA'
        self.TLWCOR     = 'TLWCOR'
        self.TVWCOR     = 'TVWCOR'
        self.QTWCOR     = 'QTWCOR'
        self.QCWCOR     = 'QCWCOR'
        self.QIWCOR     = 'QIWCOR'
        self.HFCOR      = 'HFCOR'
        self.HFCORA     = 'HFCORA'
        self.UCORA      = 'UCORA'
        self.VCORA      = 'VCORA'
        self.UPGFCOR    = 'UPGFCOR'
        self.VPGFCOR    = 'VPGFCOR'
        self.WPGFCOR    = 'WPGFCOR'
        self.UWCOR      = 'UWCOR'
        self.VWCOR      = 'VWCOR'
        self.UWSBCOR    = 'UWSBCOR'
        self.VWSBCOR    = 'VWSBCOR'
        self.MFCOR      = 'MFCOR'
        self.MFHCOR     = 'MFHCOR'
        self.MFHCORA    = 'MFHCORA'
        self.MFTLCOR    = 'MFTLCOR'
        self.MFTLCORA   = 'MFTLCORA'
        self.MFTVCOR    = 'MFTVCOR'
        self.MFTVCORA   = 'MFTVCORA'
        self.MFQTCOR    = 'MFQTCOR'
        self.MFQTCORA   = 'MFQTCORA'
        self.RUWCOR     = 'RUWCOR'
        self.RVWCOR     = 'RVWCOR'
        self.RWWCOR     = 'RWWCOR'
        self.CDN        = 'CDN'
        self.WCDN       = 'WCDN'
        self.UCDN       = 'UCDN'
        self.VCDN       = 'VCDN'
        self.MSECDN     = 'MSECDN'
        self.DSECDN     = 'DSECDN'
        self.TLCDN      = 'TLCDN'
        self.TACDN      = 'TACDN'
        self.TVCDN      = 'TVCDN'
        self.TVCDNA     = 'TVCDNA'
        self.QTCDN      = 'QTCDN'
        self.QNCDN      = 'QNCDN'
        self.QPCDN      = 'QPCDN'
        self.WCDNA      = 'WCDNA'
        self.TLWCDN     = 'TLWCDN'
        self.TVWCDN     = 'TVWCDN'
        self.QTWCDN     = 'QTWCDN'
        self.QCWCDN     = 'QCWCDN'
        self.QIWCDN     = 'QIWCDN'
        self.HFCDN      = 'HFCDN'
        self.HFCDNA     = 'HFCDNA'
        self.UCDNA      = 'UCDNA'
        self.VCDNA      = 'VCDNA'
        self.UPGFCDN    = 'UPGFCDN'
        self.VPGFCDN    = 'VPGFCDN'
        self.WPGFCDN    = 'WPGFCDN'
        self.UWCDN      = 'UWCDN'
        self.VWCDN      = 'VWCDN'
        self.UWSBCDN    = 'UWSBCDN'
        self.VWSBCDN    = 'VWSBCDN'
        self.MFCDN      = 'MFCDN'
        self.MFHCDN     = 'MFHCDN'
        self.MFHCDNA    = 'MFHCDNA'
        self.MFTLCDN    = 'MFTLCDN'
        self.MFTLCDNA   = 'MFTLCDNA'
        self.MFTVCDN    = 'MFTVCDN'
        self.MFTVCDNA   = 'MFTVCDNA'
        self.MFQTCDN    = 'MFQTCDN'
        self.MFQTCDNA   = 'MFQTCDNA'
        self.RUWCDN     = 'RUWCDN'
        self.RVWCDN     = 'RVWCDN'
        self.RWWCDN     = 'RWWCDN'
        self.SUP        = 'SUP'
        self.WSUP       = 'WSUP'
        self.USUP       = 'USUP'
        self.VSUP       = 'VSUP'
        self.MSESUP     = 'MSESUP'
        self.DSESUP     = 'DSESUP'
        self.TLSUP      = 'TLSUP'
        self.TASUP      = 'TASUP'
        self.TVSUP      = 'TVSUP'
        self.TVSUPA     = 'TVSUPA'
        self.QTSUP      = 'QTSUP'
        self.QNSUP      = 'QNSUP'
        self.QPSUP      = 'QPSUP'
        self.WSUPA      = 'WSUPA'
        self.TLWSUP     = 'TLWSUP'
        self.TVWSUP     = 'TVWSUP'
        self.QTWSUP     = 'QTWSUP'
        self.QCWSUP     = 'QCWSUP'
        self.QIWSUP     = 'QIWSUP'
        self.HFSUP      = 'HFSUP'
        self.HFSUPA     = 'HFSUPA'
        self.USUPA      = 'USUPA'
        self.VSUPA      = 'VSUPA'
        self.UPGFSUP    = 'UPGFSUP'
        self.VPGFSUP    = 'VPGFSUP'
        self.WPGFSUP    = 'WPGFSUP'
        self.UWSUP      = 'UWSUP'
        self.VWSUP      = 'VWSUP'
        self.UWSBSUP    = 'UWSBSUP'
        self.VWSBSUP    = 'VWSBSUP'
        self.MFSUP      = 'MFSUP'
        self.MFHSUP     = 'MFHSUP'
        self.MFHSUPA    = 'MFHSUPA'
        self.MFTLSUP    = 'MFTLSUP'
        self.MFTLSUPA   = 'MFTLSUPA'
        self.MFTVSUP    = 'MFTVSUP'
        self.MFTVSUPA   = 'MFTVSUPA'
        self.MFQTSUP    = 'MFQTSUP'
        self.MFQTSUPA   = 'MFQTSUPA'
        self.RUWSUP     = 'RUWSUP'
        self.RVWSUP     = 'RVWSUP'
        self.RWWSUP     = 'RWWSUP'
        self.SDN        = 'SDN'
        self.WSDN       = 'WSDN'
        self.USDN       = 'USDN'
        self.VSDN       = 'VSDN'
        self.MSESDN     = 'MSESDN'
        self.DSESDN     = 'DSESDN'
        self.TLSDN      = 'TLSDN'
        self.TASDN      = 'TASDN'
        self.TVSDN      = 'TVSDN'
        self.TVSDNA     = 'TVSDNA'
        self.QTSDN      = 'QTSDN'
        self.QNSDN      = 'QNSDN'
        self.QPSDN      = 'QPSDN'
        self.WSDNA      = 'WSDNA'
        self.TLWSDN     = 'TLWSDN'
        self.TVWSDN     = 'TVWSDN'
        self.QTWSDN     = 'QTWSDN'
        self.QCWSDN     = 'QCWSDN'
        self.QIWSDN     = 'QIWSDN'
        self.HFSDN      = 'HFSDN'
        self.HFSDNA     = 'HFSDNA'
        self.USDNA      = 'USDNA'
        self.VSDNA      = 'VSDNA'
        self.UPGFSDN    = 'UPGFSDN'
        self.VPGFSDN    = 'VPGFSDN'
        self.WPGFSDN    = 'WPGFSDN'
        self.UWSDN      = 'UWSDN'
        self.VWSDN      = 'VWSDN'
        self.UWSBSDN    = 'UWSBSDN'
        self.VWSBSDN    = 'VWSBSDN'
        self.MFSDN      = 'MFSDN'
        self.MFHSDN     = 'MFHSDN'
        self.MFHSDNA    = 'MFHSDNA'
        self.MFTLSDN    = 'MFTLSDN'
        self.MFTLSDNA   = 'MFTLSDNA'
        self.MFTVSDN    = 'MFTVSDN'
        self.MFTVSDNA   = 'MFTVSDNA'
        self.MFQTSDN    = 'MFQTSDN'
        self.MFQTSDNA   = 'MFQTSDNA'
        self.RUWSDN     = 'RUWSDN'
        self.RVWSDN     = 'RVWSDN'
        self.RWWSDN     = 'RWWSDN'
        self.ENV        = 'ENV'
        self.WENV       = 'WENV'
        self.UENV       = 'UENV'
        self.VENV       = 'VENV'
        self.MSEENV     = 'MSEENV'
        self.DSEENV     = 'DSEENV'
        self.TLENV      = 'TLENV'
        self.TAENV      = 'TAENV'
        self.TVENV      = 'TVENV'
        self.TVENVA     = 'TVENVA'
        self.QTENV      = 'QTENV'
        self.QNENV      = 'QNENV'
        self.QPENV      = 'QPENV'
        self.WENVA      = 'WENVA'
        self.TLWENV     = 'TLWENV'
        self.TVWENV     = 'TVWENV'
        self.QTWENV     = 'QTWENV'
        self.QCWENV     = 'QCWENV'
        self.QIWENV     = 'QIWENV'
        self.HFENV      = 'HFENV'
        self.HFENVA     = 'HFENVA'
        self.UENVA      = 'UENVA'
        self.VENVA      = 'VENVA'
        self.UPGFENV    = 'UPGFENV'
        self.VPGFENV    = 'VPGFENV'
        self.WPGFENV    = 'WPGFENV'
        self.UWENV      = 'UWENV'
        self.VWENV      = 'VWENV'
        self.UWSBENV    = 'UWSBENV'
        self.VWSBENV    = 'VWSBENV'
        self.MFENV      = 'MFENV'
        self.MFHENV     = 'MFHENV'
        self.MFHENVA    = 'MFHENVA'
        self.MFTLENV    = 'MFTLENV'
        self.MFTLENVA   = 'MFTLENVA'
        self.MFTVENV    = 'MFTVENV'
        self.MFTVENVA   = 'MFTVENVA'
        self.MFQTENV    = 'MFQTENV'
        self.MFQTENVA   = 'MFQTENVA'
        self.RUWENV     = 'RUWENV'
        self.RVWENV     = 'RVWENV'
        self.RWWENV     = 'RWWENV'
        self.QTFLUX     = 'QTFLUX'
        self.QTFLUXS    = 'QTFLUXS'
        self.QPFLUX     = 'QPFLUX'
        self.QPFLUXS    = 'QPFLUXS'
        self.QTLSADV    = 'QTLSADV'
        self.QPLSADV    = 'QPLSADV'
        self.QC         = 'QC'
        self.QI         = 'QI'
        self.QR         = 'QR'
        self.QS         = 'QS'
        self.QG         = 'QG'
        self.QCCLD      = 'QCCLD'
        self.QICLD      = 'QICLD'
        self.QCCOR      = 'QCCOR'
        self.QICOR      = 'QICOR'
        self.QCCDN      = 'QCCDN'
        self.QICDN      = 'QICDN'
        self.QCSUP      = 'QCSUP'
        self.QISUP      = 'QISUP'
        self.QCSDN      = 'QCSDN'
        self.QISDN      = 'QISDN'
        self.QCENV      = 'QCENV'
        self.QIENV      = 'QIENV'                          

    def __iter__(self):
        for each in self.__dict__.keys():
            yield self.__getattribute__(each)

#To assint the label of the family of 
#variables

def ncload(name,file_l,calendar,vars_1d=[],vars_2d=[],vars_diurnal=[],dates=[],dates_d=[]):

    #load class 
    label=variables() 

    #put the objets in class

    label.datei=dt.datetime(dates[0][0],dates[0][1],dates[0][2],dates[0][3])
    label.datef=dt.datetime(dates[1][0],dates[1][1],dates[1][2],dates[1][3])

    if len(dates_d)>0:
        label.datei_diurnal=dt.datetime(dates_d[0][0],dates_d[0][1],dates_d[0][2],dates_d[0][3])
        label.datef_diurnal=dt.datetime(dates_d[1][0],dates_d[1][1],dates_d[1][2],dates_d[1][3])
    else:
        print('Diurnal dates experiment was no defined')

    label.name=name
    label.var1d=vars_1d
    label.var2d=vars_2d
    label.vars_diurnal=vars_diurnal

    # Your filename
    nc_file    = '%s'%(file_l)


    # Dataset is the class behavior to open the file
    # and create an instance of the ncCDF4 class
    nc_v = Dataset(nc_file, 'r')

    label.nc_f       =nc_v 

    
    label.z          = nc_v.variables['z'         ]   
    label.time       = nc_v.variables['time'      ]
    label.p          = nc_v.variables['p'         ]        
    label.SST        = nc_v.variables['SST'       ]
    label.Ps         = nc_v.variables['Ps'        ]
    label.CLD245     = nc_v.variables['CLD245'    ]
    label.PREC       = nc_v.variables['PREC'      ]
    label.PW         = nc_v.variables['PW'        ]
    label.IWP        = nc_v.variables['IWP'       ]
    label.GWP        = nc_v.variables['GWP'       ]
    label.CAPE       = nc_v.variables['CAPE'       ]
    label.CAPEOBS    = nc_v.variables['CAPEOBS'       ]
    label.CIN        = nc_v.variables['CIN'       ]
    label.CINOBS     = nc_v.variables['CINOBS']
    label.LWNS       = nc_v.variables['LWNS']
    label.LWNT       = nc_v.variables['LWNT']
    label.LWNTOA     = nc_v.variables['LWNTOA']
    label.LWNSC      = nc_v.variables['LWNSC']
    label.LWNTOAC    = nc_v.variables['LWNTOAC']
    label.LWDS       = nc_v.variables['LWDS']
    label.SWNS       = nc_v.variables['SWNS']
    label.SWNT       = nc_v.variables['SWNT']
    label.SWNTOA     = nc_v.variables['SWNTOA']
    label.SWNSC      = nc_v.variables['SWNSC']
    label.SWNTOAC    = nc_v.variables['SWNTOAC']
    label.SWDS       = nc_v.variables['SWDS']
    label.SOLIN      = nc_v.variables['SOLIN']
    label.SSTOBS     = nc_v.variables['SSTOBS']
    label.LHFOBS     = nc_v.variables['LHFOBS']
    label.SHFOBS     = nc_v.variables['SHFOBS']
    label.CLDLOW     = nc_v.variables['CLDLOW']
    label.ISCCPTOT   = nc_v.variables['ISCCPTOT'  ]
    label.ISCCPHGH   = nc_v.variables['ISCCPHGH'  ]
    label.MODISTOT   = nc_v.variables['MODISTOT'  ]
    label.MODISMID   = nc_v.variables['MODISMID'  ]
    label.MODISREL   = nc_v.variables['MODISREL'  ]
    label.MODISIWP   = nc_v.variables['MODISIWP'  ]
    label.MODISTOTL  = nc_v.variables['MODISTOTL' ]
    label.ISCCPALB   = nc_v.variables['ISCCPALB'  ]
    label.MODISTAUL  = nc_v.variables['MODISTAUL' ]
    label.MODISTAUI  = nc_v.variables['MODISTAUI' ]
    label.MODISPTOP  = nc_v.variables['MODISPTOP' ]
    label.MISRZTOP   = nc_v.variables['MISRZTOP'  ]
    label.ZINV       = nc_v.variables['ZINV'      ]
    label.ZINV2      = nc_v.variables['ZINV2'     ]
    label.ZCT        = nc_v.variables['ZCT'       ]
    label.ZCT2       = nc_v.variables['ZCT2'      ]
    label.ZCTMAX     = nc_v.variables['ZCTMAX'    ]
    label.ZCB        = nc_v.variables['ZCB'       ]
    label.ZCB2       = nc_v.variables['ZCB2'      ]
    label.ZCBMIN     = nc_v.variables['ZCBMIN'    ]
    label.LWP        = nc_v.variables['LWP'       ]
    label.LWP2       = nc_v.variables['LWP2'      ]
    label.PRECMN     = nc_v.variables['PRECMN'    ]
    label.PREC2      = nc_v.variables['PREC2'     ]
    label.PRECMAX    = nc_v.variables['PRECMAX'   ]
    label.NCMN       = nc_v.variables['NCMN'      ]
    label.NRMN       = nc_v.variables['NRMN'      ]
    label.AREAPRTHR  = nc_v.variables['AREAPRTHR' ]
    label.PRES       = nc_v.variables['PRES'      ]
    label.U          = nc_v.variables['U'         ]
    label.V          = nc_v.variables['V'         ]
    label.UOBS       = nc_v.variables['UOBS'      ]
    label.VOBS       = nc_v.variables['VOBS'      ]
    label.WOBS       = nc_v.variables['WOBS'      ]
    label.RHO        = nc_v.variables['RHO'       ]
    label.MSE        = nc_v.variables['MSE'       ]
    label.DSE        = nc_v.variables['DSE'       ]
    label.SSE        = nc_v.variables['SSE'       ]
    label.THETAE     = nc_v.variables['THETAE'    ]
    label.THETA      = nc_v.variables['THETA'     ]
    label.THETAV     = nc_v.variables['THETAV'    ]
    label.THETAL     = nc_v.variables['THETAL'    ]
    label.TABS       = nc_v.variables['TABS'      ]
    label.TABSOBS    = nc_v.variables['TABSOBS'   ]
    label.TL         = nc_v.variables['TL'        ]
    label.QT         = nc_v.variables['QT'        ]
    label.QV         = nc_v.variables['QV'        ]
    label.QVOBS      = nc_v.variables['QVOBS'     ]
    label.TTEND      = nc_v.variables['TTEND'     ]
    label.QTEND      = nc_v.variables['QTEND'     ]
    label.QCL        = nc_v.variables['QCL'       ]
    label.QCI        = nc_v.variables['QCI'       ]
    label.QPL        = nc_v.variables['QPL'       ]
    label.QPI        = nc_v.variables['QPI'       ]
    label.QN         = nc_v.variables['QN'        ]
    label.QP         = nc_v.variables['QP'        ]
    label.QSAT       = nc_v.variables['QSAT'      ]
    label.QCOND      = nc_v.variables['QCOND'     ]
    label.PRECIP     = nc_v.variables['PRECIP'    ]
    label.LHF        = nc_v.variables['LHF'       ]
    label.SHF        = nc_v.variables['SHF'       ]
    label.RELH       = nc_v.variables['RELH'      ]
    label.TLFLUX     = nc_v.variables['TLFLUX'    ]
    label.TLFLUXS    = nc_v.variables['TLFLUXS'   ]
    label.TVFLUX     = nc_v.variables['TVFLUX'    ]
    label.QCFLUX     = nc_v.variables['QCFLUX'    ]
    label.QIFLUX     = nc_v.variables['QIFLUX'    ]
    label.UW         = nc_v.variables['UW'        ]
    label.UWSB       = nc_v.variables['UWSB'      ]
    label.VW         = nc_v.variables['VW'        ]
    label.VWSB       = nc_v.variables['VWSB'      ]
    #label.RADLWUP    = nc_v.variables['RADLWUP'   ]
    #label.RADLWDN    = nc_v.variables['RADLWDN'   ]
    #label.RADSWUP    = nc_v.variables['RADSWUP'   ]
    #label.RADSWDN    = nc_v.variables['RADSWDN'   ]
    #label.RADQRLW    = nc_v.variables['RADQRLW'   ]
    #label.RADQRSW    = nc_v.variables['RADQRSW'   ]
    #label.RADQR      = nc_v.variables['RADQR'     ]
    #label.RADQRS     = nc_v.variables['RADQRS'    ]
    #label.RADQRC     = nc_v.variables['RADQRC'    ]
    label.Q1C        = nc_v.variables['Q1C'       ]
    label.Q2         = nc_v.variables['Q2'        ]
    label.U2         = nc_v.variables['U2'        ]
    label.V2         = nc_v.variables['V2'        ]
    label.W2         = nc_v.variables['W2'        ]
    label.TL2        = nc_v.variables['TL2'       ]
    label.TQ         = nc_v.variables['TQ'        ]
    label.QT2        = nc_v.variables['QT2'       ]
    label.QC2        = nc_v.variables['QC2'       ]
    label.QI2        = nc_v.variables['QI2'       ]
    label.QS2        = nc_v.variables['QS2'       ]
    label.W3         = nc_v.variables['W3'        ]
    label.AUP        = nc_v.variables['AUP'       ]
    label.WSKEW      = nc_v.variables['WSKEW'     ]
    label.TKE        = nc_v.variables['TKE'       ]
    label.TKES       = nc_v.variables['TKES'      ]
    label.TK         = nc_v.variables['TK'        ]
    label.TKH        = nc_v.variables['TKH'       ]
    label.HLADV      = nc_v.variables['HLADV'     ]
    label.HLDIFF     = nc_v.variables['HLDIFF'    ]
    label.HLLAT      = nc_v.variables['HLLAT'     ]
    label.HLRAD      = nc_v.variables['HLRAD'     ]
    #label.QTADV      = nc_v.variables['QTADV'     ]
    #label.QTDIFF     = nc_v.variables['QTDIFF'    ]
    #label.QTSINK     = nc_v.variables['QTSINK'    ]
    #label.QTSRC      = nc_v.variables['QTSRC'     ]
    #label.QPADV      = nc_v.variables['QPADV'     ]
    #label.QPDIFF     = nc_v.variables['QPDIFF'    ]
    #label.QPFALL     = nc_v.variables['QPFALL'    ]
    #label.QPSRC      = nc_v.variables['QPSRC'     ]
    #label.QPEVP      = nc_v.variables['QPEVP'     ]
    label.SHEAR      = nc_v.variables['SHEAR'     ]
    label.SHEARS     = nc_v.variables['SHEARS'    ]
    label.BUOYA      = nc_v.variables['BUOYA'     ]
    label.BUOYAS     = nc_v.variables['BUOYAS'    ]
    label.ADVTR      = nc_v.variables['ADVTR'     ]
    label.PRESSTR    = nc_v.variables['PRESSTR'   ]
    label.ADVTRS     = nc_v.variables['ADVTRS'    ]
    label.DIFTR      = nc_v.variables['DIFTR'     ]
    label.DISSIP     = nc_v.variables['DISSIP'    ]
    label.DISSIPS    = nc_v.variables['DISSIPS'   ]
    label.WUADV      = nc_v.variables['WUADV'     ]
    label.WVADV      = nc_v.variables['WVADV'     ]
    label.WUPRES     = nc_v.variables['WUPRES'    ]
    label.WVPRES     = nc_v.variables['WVPRES'    ]
    label.WUANIZ     = nc_v.variables['WUANIZ'    ]
    label.WVANIZ     = nc_v.variables['WVANIZ'    ]
    label.WUSHEAR    = nc_v.variables['WUSHEAR'   ]
    label.WVSHEAR    = nc_v.variables['WVSHEAR'   ]
    label.WUBUOY     = nc_v.variables['WUBUOY'    ]
    label.WVBUOY     = nc_v.variables['WVBUOY'    ]
    label.WUDIFF     = nc_v.variables['WUDIFF'    ]
    label.WVDIFF     = nc_v.variables['WVDIFF'    ]
    label.W2ADV      = nc_v.variables['W2ADV'     ]
    label.W2PRES     = nc_v.variables['W2PRES'    ]
    label.W2REDIS    = nc_v.variables['W2REDIS'   ]
    label.W2BUOY     = nc_v.variables['W2BUOY'    ]
    label.W2DIFF     = nc_v.variables['W2DIFF'    ]
    label.TWGRAD     = nc_v.variables['TWGRAD'    ]
    label.TWADV      = nc_v.variables['TWADV'     ]
    label.TWDIFF     = nc_v.variables['TWDIFF'    ]
    label.TWBUOY     = nc_v.variables['TWBUOY'    ]
    label.TWPRES     = nc_v.variables['TWPRES'    ]
    label.TWPREC     = nc_v.variables['TWPREC'    ]
    label.QWGRAD     = nc_v.variables['QWGRAD'    ]
    label.QWADV      = nc_v.variables['QWADV'     ]
    label.QWDIFF     = nc_v.variables['QWDIFF'    ]
    label.QWBUOY     = nc_v.variables['QWBUOY'    ]
    label.QWPRES     = nc_v.variables['QWPRES'    ]
    label.QWPREC     = nc_v.variables['QWPREC'    ]
    label.T2ADVTR    = nc_v.variables['T2ADVTR'   ]
    label.T2GRAD     = nc_v.variables['T2GRAD'    ]
    label.T2DISSIP   = nc_v.variables['T2DISSIP'  ]
    label.T2DIFTR    = nc_v.variables['T2DIFTR'   ]
    label.T2PREC     = nc_v.variables['T2PREC'    ]
    label.Q2ADVTR    = nc_v.variables['Q2ADVTR'   ]
    label.Q2GRAD     = nc_v.variables['Q2GRAD'    ]
    label.Q2DISSIP   = nc_v.variables['Q2DISSIP'  ]
    label.Q2DIFTR    = nc_v.variables['Q2DIFTR'   ]
    label.Q2PREC     = nc_v.variables['Q2PREC'    ]
    label.HYDRO      = nc_v.variables['HYDRO'     ]
    label.MCUP       = nc_v.variables['MCUP'      ]
    label.MCDNS      = nc_v.variables['MCDNS'     ]
    label.MCDNU      = nc_v.variables['MCDNU'     ]
    label.MC         = nc_v.variables['MC'        ]
    label.CORECL     = nc_v.variables['CORECL'    ]
    label.COREDNCL   = nc_v.variables['COREDNCL'  ]
    label.MCRUP      = nc_v.variables['MCRUP'     ]
    label.MCRDNS     = nc_v.variables['MCRDNS'    ]
    label.MCRDNU     = nc_v.variables['MCRDNU'    ]
    label.MCR        = nc_v.variables['MCR'       ]
    label.QVTEND     = nc_v.variables['QVTEND'    ]
    label.QHTEND     = nc_v.variables['QHTEND'    ]
    label.QNUDGE     = nc_v.variables['QNUDGE'    ]
    label.THTEND     = nc_v.variables['THTEND'    ]
    label.TVTEND     = nc_v.variables['TVTEND'    ]
    label.TNUDGE     = nc_v.variables['TNUDGE'    ]
    label.WSTAR3     = nc_v.variables['WSTAR3'    ]
    label.UADV       = nc_v.variables['UADV'      ]
    label.VADV       = nc_v.variables['VADV'      ]
    label.UDIFF      = nc_v.variables['UDIFF'     ]
    label.VDIFF      = nc_v.variables['VDIFF'     ]
    label.UNUDGE     = nc_v.variables['UNUDGE'    ]
    label.VNUDGE     = nc_v.variables['VNUDGE'    ]
    label.ULSADVV    = nc_v.variables['ULSADVV'   ]
    label.VLSADVV    = nc_v.variables['VLSADVV'   ]
    label.USTOR      = nc_v.variables['USTOR'     ]
    label.VSTOR      = nc_v.variables['VSTOR'     ]
    label.UTENDCOR   = nc_v.variables['UTENDCOR'  ]
    label.URESID     = nc_v.variables['URESID'    ]
    label.VTENDCOR   = nc_v.variables['VTENDCOR'  ]
    label.VRESID     = nc_v.variables['VRESID'    ]
    label.HLSTOR     = nc_v.variables['HLSTOR'    ]
    label.QTSTOR     = nc_v.variables['QTSTOR'    ]
    #label.RADQRCLW   = nc_v.variables['RADQRCLW'  ]
    #label.RADQRCSW   = nc_v.variables['RADQRCSW'  ]
    label.CLD        = nc_v.variables['CLD'       ]
    label.WCLD       = nc_v.variables['WCLD'      ]
    label.UCLD       = nc_v.variables['UCLD'      ]
    label.VCLD       = nc_v.variables['VCLD'      ]
    label.MSECLD     = nc_v.variables['MSECLD'    ]
    label.DSECLD     = nc_v.variables['DSECLD'    ]
    label.TLCLD      = nc_v.variables['TLCLD'     ]
    label.TACLD      = nc_v.variables['TACLD'     ]
    label.TVCLD      = nc_v.variables['TVCLD'     ]
    label.TVCLDA     = nc_v.variables['TVCLDA'    ]
    label.QTCLD      = nc_v.variables['QTCLD'     ]
    label.QNCLD      = nc_v.variables['QNCLD'     ]
    label.QPCLD      = nc_v.variables['QPCLD'     ]
    label.WCLDA      = nc_v.variables['WCLDA'     ]
    label.TLWCLD     = nc_v.variables['TLWCLD'    ]
    label.TVWCLD     = nc_v.variables['TVWCLD'    ]
    label.QTWCLD     = nc_v.variables['QTWCLD'    ]
    label.QCWCLD     = nc_v.variables['QCWCLD'    ]
    label.QIWCLD     = nc_v.variables['QIWCLD'    ]
    label.HFCLD      = nc_v.variables['HFCLD'     ]
    label.HFCLDA     = nc_v.variables['HFCLDA'    ]
    label.UCLDA      = nc_v.variables['UCLDA'     ]
    label.VCLDA      = nc_v.variables['VCLDA'     ]
    label.UPGFCLD    = nc_v.variables['UPGFCLD'   ]
    label.VPGFCLD    = nc_v.variables['VPGFCLD'   ]
    label.WPGFCLD    = nc_v.variables['WPGFCLD'   ]
    label.UWCLD      = nc_v.variables['UWCLD'     ]
    label.VWCLD      = nc_v.variables['VWCLD'     ]
    label.UWSBCLD    = nc_v.variables['UWSBCLD'   ]
    label.VWSBCLD    = nc_v.variables['VWSBCLD'   ]
    label.MFCLD      = nc_v.variables['MFCLD'     ]
    label.MFHCLD     = nc_v.variables['MFHCLD'    ]
    label.MFHCLDA    = nc_v.variables['MFHCLDA'   ]
    label.MFTLCLD    = nc_v.variables['MFTLCLD'   ]
    label.MFTLCLDA   = nc_v.variables['MFTLCLDA'  ]
    label.MFTVCLD    = nc_v.variables['MFTVCLD'   ]
    label.MFTVCLDA   = nc_v.variables['MFTVCLDA'  ]
    label.MFQTCLD    = nc_v.variables['MFQTCLD'   ]
    label.MFQTCLDA   = nc_v.variables['MFQTCLDA'  ]
    label.RUWCLD     = nc_v.variables['RUWCLD'    ]
    label.RVWCLD     = nc_v.variables['RVWCLD'    ]
    label.RWWCLD     = nc_v.variables['RWWCLD'    ]
    label.COR        = nc_v.variables['COR'       ]
    label.WCOR       = nc_v.variables['WCOR'      ]
    label.UCOR       = nc_v.variables['UCOR'      ]
    label.VCOR       = nc_v.variables['VCOR'      ]
    label.MSECOR     = nc_v.variables['MSECOR'    ]
    label.DSECOR     = nc_v.variables['DSECOR'    ]
    label.TLCOR      = nc_v.variables['TLCOR'     ]
    label.TACOR      = nc_v.variables['TACOR'     ]
    label.TVCOR      = nc_v.variables['TVCOR'     ]
    label.TVCORA     = nc_v.variables['TVCORA'    ]
    label.QTCOR      = nc_v.variables['QTCOR'     ]
    label.QNCOR      = nc_v.variables['QNCOR'     ]
    label.QPCOR      = nc_v.variables['QPCOR'     ]
    label.WCORA      = nc_v.variables['WCORA'     ]
    label.TLWCOR     = nc_v.variables['TLWCOR'    ]
    label.TVWCOR     = nc_v.variables['TVWCOR'    ]
    label.QTWCOR     = nc_v.variables['QTWCOR'    ]
    label.QCWCOR     = nc_v.variables['QCWCOR'    ]
    label.QIWCOR     = nc_v.variables['QIWCOR'    ]
    label.HFCOR      = nc_v.variables['HFCOR'     ]
    label.HFCORA     = nc_v.variables['HFCORA'    ]
    label.UCORA      = nc_v.variables['UCORA'     ]
    label.VCORA      = nc_v.variables['VCORA'     ]
    label.UPGFCOR    = nc_v.variables['UPGFCOR'   ]
    label.VPGFCOR    = nc_v.variables['VPGFCOR'   ]
    label.WPGFCOR    = nc_v.variables['WPGFCOR'   ]
    label.UWCOR      = nc_v.variables['UWCOR'     ]
    label.VWCOR      = nc_v.variables['VWCOR'     ]
    label.UWSBCOR    = nc_v.variables['UWSBCOR'   ]
    label.VWSBCOR    = nc_v.variables['VWSBCOR'   ]
    label.MFCOR      = nc_v.variables['MFCOR'     ]
    label.MFHCOR     = nc_v.variables['MFHCOR'    ]
    label.MFHCORA    = nc_v.variables['MFHCORA'   ]
    label.MFTLCOR    = nc_v.variables['MFTLCOR'   ]
    label.MFTLCORA   = nc_v.variables['MFTLCORA'  ]
    label.MFTVCOR    = nc_v.variables['MFTVCOR'   ]
    label.MFTVCORA   = nc_v.variables['MFTVCORA'  ]
    label.MFQTCOR    = nc_v.variables['MFQTCOR'   ]
    label.MFQTCORA   = nc_v.variables['MFQTCORA'  ]
    label.RUWCOR     = nc_v.variables['RUWCOR'    ]
    label.RVWCOR     = nc_v.variables['RVWCOR'    ]
    label.RWWCOR     = nc_v.variables['RWWCOR'    ]
    label.CDN        = nc_v.variables['CDN'       ]
    label.WCDN       = nc_v.variables['WCDN'      ]
    label.UCDN       = nc_v.variables['UCDN'      ]
    label.VCDN       = nc_v.variables['VCDN'      ]
    label.MSECDN     = nc_v.variables['MSECDN'    ]
    label.DSECDN     = nc_v.variables['DSECDN'    ]
    label.TLCDN      = nc_v.variables['TLCDN'     ]
    label.TACDN      = nc_v.variables['TACDN'     ]
    label.TVCDN      = nc_v.variables['TVCDN'     ]
    label.TVCDNA     = nc_v.variables['TVCDNA'    ]
    label.QTCDN      = nc_v.variables['QTCDN'     ]
    label.QNCDN      = nc_v.variables['QNCDN'     ]
    label.QPCDN      = nc_v.variables['QPCDN'     ]
    label.WCDNA      = nc_v.variables['WCDNA'     ]
    label.TLWCDN     = nc_v.variables['TLWCDN'    ]
    label.TVWCDN     = nc_v.variables['TVWCDN'    ]
    label.QTWCDN     = nc_v.variables['QTWCDN'    ]
    label.QCWCDN     = nc_v.variables['QCWCDN'    ]
    label.QIWCDN     = nc_v.variables['QIWCDN'    ]
    label.HFCDN      = nc_v.variables['HFCDN'     ]
    label.HFCDNA     = nc_v.variables['HFCDNA'    ]
    label.UCDNA      = nc_v.variables['UCDNA'     ]
    label.VCDNA      = nc_v.variables['VCDNA'     ]
    label.UPGFCDN    = nc_v.variables['UPGFCDN'   ]
    label.VPGFCDN    = nc_v.variables['VPGFCDN'   ]
    label.WPGFCDN    = nc_v.variables['WPGFCDN'   ]
    label.UWCDN      = nc_v.variables['UWCDN'     ]
    label.VWCDN      = nc_v.variables['VWCDN'     ]
    label.UWSBCDN    = nc_v.variables['UWSBCDN'   ]
    label.VWSBCDN    = nc_v.variables['VWSBCDN'   ]
    label.MFCDN      = nc_v.variables['MFCDN'     ]
    label.MFHCDN     = nc_v.variables['MFHCDN'    ]
    label.MFHCDNA    = nc_v.variables['MFHCDNA'   ]
    label.MFTLCDN    = nc_v.variables['MFTLCDN'   ]
    label.MFTLCDNA   = nc_v.variables['MFTLCDNA'  ]
    label.MFTVCDN    = nc_v.variables['MFTVCDN'   ]
    label.MFTVCDNA   = nc_v.variables['MFTVCDNA'  ]
    label.MFQTCDN    = nc_v.variables['MFQTCDN'   ]
    label.MFQTCDNA   = nc_v.variables['MFQTCDNA'  ]
    label.RUWCDN     = nc_v.variables['RUWCDN'    ]
    label.RVWCDN     = nc_v.variables['RVWCDN'    ]
    label.RWWCDN     = nc_v.variables['RWWCDN'    ]
    label.SUP        = nc_v.variables['SUP'       ]
    label.WSUP       = nc_v.variables['WSUP'      ]
    label.USUP       = nc_v.variables['USUP'      ]
    label.VSUP       = nc_v.variables['VSUP'      ]
    label.MSESUP     = nc_v.variables['MSESUP'    ]
    label.DSESUP     = nc_v.variables['DSESUP'    ]
    label.TLSUP      = nc_v.variables['TLSUP'     ]
    label.TASUP      = nc_v.variables['TASUP'     ]
    label.TVSUP      = nc_v.variables['TVSUP'     ]
    label.TVSUPA     = nc_v.variables['TVSUPA'    ]
    label.QTSUP      = nc_v.variables['QTSUP'     ]
    label.QNSUP      = nc_v.variables['QNSUP'     ]
    label.QPSUP      = nc_v.variables['QPSUP'     ]
    label.WSUPA      = nc_v.variables['WSUPA'     ]
    label.TLWSUP     = nc_v.variables['TLWSUP'    ]
    label.TVWSUP     = nc_v.variables['TVWSUP'    ]
    label.QTWSUP     = nc_v.variables['QTWSUP'    ]
    label.QCWSUP     = nc_v.variables['QCWSUP'    ]
    label.QIWSUP     = nc_v.variables['QIWSUP'    ]
    label.HFSUP      = nc_v.variables['HFSUP'     ]
    label.HFSUPA     = nc_v.variables['HFSUPA'    ]
    label.USUPA      = nc_v.variables['USUPA'     ]
    label.VSUPA      = nc_v.variables['VSUPA'     ]
    label.UPGFSUP    = nc_v.variables['UPGFSUP'   ]
    label.VPGFSUP    = nc_v.variables['VPGFSUP'   ]
    label.WPGFSUP    = nc_v.variables['WPGFSUP'   ]
    label.UWSUP      = nc_v.variables['UWSUP'     ]
    label.VWSUP      = nc_v.variables['VWSUP'     ]
    label.UWSBSUP    = nc_v.variables['UWSBSUP'   ]
    label.VWSBSUP    = nc_v.variables['VWSBSUP'   ]
    label.MFSUP      = nc_v.variables['MFSUP'     ]
    label.MFHSUP     = nc_v.variables['MFHSUP'    ]
    label.MFHSUPA    = nc_v.variables['MFHSUPA'   ]
    label.MFTLSUP    = nc_v.variables['MFTLSUP'   ]
    label.MFTLSUPA   = nc_v.variables['MFTLSUPA'  ]
    label.MFTVSUP    = nc_v.variables['MFTVSUP'   ]
    label.MFTVSUPA   = nc_v.variables['MFTVSUPA'  ]
    label.MFQTSUP    = nc_v.variables['MFQTSUP'   ]
    label.MFQTSUPA   = nc_v.variables['MFQTSUPA'  ]
    label.RUWSUP     = nc_v.variables['RUWSUP'    ]
    label.RVWSUP     = nc_v.variables['RVWSUP'    ]
    label.RWWSUP     = nc_v.variables['RWWSUP'    ]
    label.SDN        = nc_v.variables['SDN'       ]
    label.WSDN       = nc_v.variables['WSDN'      ]
    label.USDN       = nc_v.variables['USDN'      ]
    label.VSDN       = nc_v.variables['VSDN'      ]
    label.MSESDN     = nc_v.variables['MSESDN'    ]
    label.DSESDN     = nc_v.variables['DSESDN'    ]
    label.TLSDN      = nc_v.variables['TLSDN'     ]
    label.TASDN      = nc_v.variables['TASDN'     ]
    label.TVSDN      = nc_v.variables['TVSDN'     ]
    label.TVSDNA     = nc_v.variables['TVSDNA'    ]
    label.QTSDN      = nc_v.variables['QTSDN'     ]
    label.QNSDN      = nc_v.variables['QNSDN'     ]
    label.QPSDN      = nc_v.variables['QPSDN'     ]
    label.WSDNA      = nc_v.variables['WSDNA'     ]
    label.TLWSDN     = nc_v.variables['TLWSDN'    ]
    label.TVWSDN     = nc_v.variables['TVWSDN'    ]
    label.QTWSDN     = nc_v.variables['QTWSDN'    ]
    label.QCWSDN     = nc_v.variables['QCWSDN'    ]
    label.QIWSDN     = nc_v.variables['QIWSDN'    ]
    label.HFSDN      = nc_v.variables['HFSDN'     ]
    label.HFSDNA     = nc_v.variables['HFSDNA'    ]
    label.USDNA      = nc_v.variables['USDNA'     ]
    label.VSDNA      = nc_v.variables['VSDNA'     ]
    label.UPGFSDN    = nc_v.variables['UPGFSDN'   ]
    label.VPGFSDN    = nc_v.variables['VPGFSDN'   ]
    label.WPGFSDN    = nc_v.variables['WPGFSDN'   ]
    label.UWSDN      = nc_v.variables['UWSDN'     ]
    label.VWSDN      = nc_v.variables['VWSDN'     ]
    label.UWSBSDN    = nc_v.variables['UWSBSDN'   ]
    label.VWSBSDN    = nc_v.variables['VWSBSDN'   ]
    label.MFSDN      = nc_v.variables['MFSDN'     ]
    label.MFHSDN     = nc_v.variables['MFHSDN'    ]
    label.MFHSDNA    = nc_v.variables['MFHSDNA'   ]
    label.MFTLSDN    = nc_v.variables['MFTLSDN'   ]
    label.MFTLSDNA   = nc_v.variables['MFTLSDNA'  ]
    label.MFTVSDN    = nc_v.variables['MFTVSDN'   ]
    label.MFTVSDNA   = nc_v.variables['MFTVSDNA'  ]
    label.MFQTSDN    = nc_v.variables['MFQTSDN'   ]
    label.MFQTSDNA   = nc_v.variables['MFQTSDNA'  ]
    label.RUWSDN     = nc_v.variables['RUWSDN'    ]
    label.RVWSDN     = nc_v.variables['RVWSDN'    ]
    label.RWWSDN     = nc_v.variables['RWWSDN'    ]
    label.ENV        = nc_v.variables['ENV'       ]
    label.WENV       = nc_v.variables['WENV'      ]
    label.UENV       = nc_v.variables['UENV'      ]
    label.VENV       = nc_v.variables['VENV'      ]
    label.MSEENV     = nc_v.variables['MSEENV'    ]
    label.DSEENV     = nc_v.variables['DSEENV'    ]
    label.TLENV      = nc_v.variables['TLENV'     ]
    label.TAENV      = nc_v.variables['TAENV'     ]
    label.TVENV      = nc_v.variables['TVENV'     ]
    label.TVENVA     = nc_v.variables['TVENVA'    ]
    label.QTENV      = nc_v.variables['QTENV'     ]
    label.QNENV      = nc_v.variables['QNENV'     ]
    label.QPENV      = nc_v.variables['QPENV'     ]
    label.WENVA      = nc_v.variables['WENVA'     ]
    label.TLWENV     = nc_v.variables['TLWENV'    ]
    label.TVWENV     = nc_v.variables['TVWENV'    ]
    label.QTWENV     = nc_v.variables['QTWENV'    ]
    label.QCWENV     = nc_v.variables['QCWENV'    ]
    label.QIWENV     = nc_v.variables['QIWENV'    ]
    label.HFENV      = nc_v.variables['HFENV'     ]
    label.HFENVA     = nc_v.variables['HFENVA'    ]
    label.UENVA      = nc_v.variables['UENVA'     ]
    label.VENVA      = nc_v.variables['VENVA'     ]
    label.UPGFENV    = nc_v.variables['UPGFENV'   ]
    label.VPGFENV    = nc_v.variables['VPGFENV'   ]
    label.WPGFENV    = nc_v.variables['WPGFENV'   ]
    label.UWENV      = nc_v.variables['UWENV'     ]
    label.VWENV      = nc_v.variables['VWENV'     ]
    label.UWSBENV    = nc_v.variables['UWSBENV'   ]
    label.VWSBENV    = nc_v.variables['VWSBENV'   ]
    label.MFENV      = nc_v.variables['MFENV'     ]
    label.MFHENV     = nc_v.variables['MFHENV'    ]
    label.MFHENVA    = nc_v.variables['MFHENVA'   ]
    label.MFTLENV    = nc_v.variables['MFTLENV'   ]
    label.MFTLENVA   = nc_v.variables['MFTLENVA'  ]
    label.MFTVENV    = nc_v.variables['MFTVENV'   ]
    label.MFTVENVA   = nc_v.variables['MFTVENVA'  ]
    label.MFQTENV    = nc_v.variables['MFQTENV'   ]
    label.MFQTENVA   = nc_v.variables['MFQTENVA'  ]
    label.RUWENV     = nc_v.variables['RUWENV'    ]
    label.RVWENV     = nc_v.variables['RVWENV'    ]
    label.RWWENV     = nc_v.variables['RWWENV'    ]
    #label.QTFLUX     = nc_v.variables['QTFLUX'    ]
    #label.QTFLUXS    = nc_v.variables['QTFLUXS'   ]
    #label.QPFLUX     = nc_v.variables['QPFLUX'    ]
    #label.QPFLUXS    = nc_v.variables['QPFLUXS'   ]
    #label.QTLSADV    = nc_v.variables['QTLSADV'   ]
    #label.QPLSADV    = nc_v.variables['QPLSADV'   ]
    label.QC         = nc_v.variables['QC'        ]
    label.QI         = nc_v.variables['QI'        ]
    label.QR         = nc_v.variables['QR'        ]
    label.QS         = nc_v.variables['QS'        ]
    label.QG         = nc_v.variables['QG'        ]
    label.QCCLD      = nc_v.variables['QCCLD'     ]
    label.QICLD      = nc_v.variables['QICLD'     ]
    label.QCCOR      = nc_v.variables['QCCOR'     ]
    label.QICOR      = nc_v.variables['QICOR'     ]
    label.QCCDN      = nc_v.variables['QCCDN'     ]
    label.QICDN      = nc_v.variables['QICDN'     ]
    label.QCSUP      = nc_v.variables['QCSUP'     ]
    label.QISUP      = nc_v.variables['QISUP'     ]
    label.QCSDN      = nc_v.variables['QCSDN'     ]
    label.QISDN      = nc_v.variables['QISDN'     ]
    label.QCENV      = nc_v.variables['QCENV'     ]
    label.QIENV      = nc_v.variables['QIENV'     ]                  

    #tu = "days  since 2014-01-01T00:00:00 +04:00:00"

    #tu = "days  since 2013-12-31T00:00:00 +04:00:00"
    #tc = "gregorian"

    tu = calendar[0] 
    tc = calendar[1]


    label.date       = num2pydate(label.time[:],units=tu,calendar=tc)

    return label 
